name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 2 days
    - cron: "0 22 */2 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.STUPID }}
        with:
          USERNAME: ${{ github.repository_owner }}
